version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directories:
      - "/local-otel/stack"
      - "/local-otel/registry"
      - "/local-otel/jobs"
      - "/local-otel/frontend/api"
      - "/local-otel/frontend/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directories:
      - "/local-otel/frontend/api"
      - "/local-otel/frontend/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
