#!/usr/bin/env zsh
set -euo pipefail

vars=(
  COPILOT_OTEL_ENABLED
  COPILOT_OTEL_ENDPOINT
  COPILOT_OTEL_PROTOCOL
  COPILOT_OTEL_CAPTURE_CONTENT
  COPILOT_OTEL_MAX_ATTRIBUTE_SIZE_CHARS
  COPILOT_MATERIALIZE_CONTENT
  COPILOT_MATERIALIZE_TRACE_LIMIT
  OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT
  COPILOT_OTEL_LOG_LEVEL
  COPILOT_OTEL_HTTP_INSTRUMENTATION
  OTEL_EXPORTER_OTLP_ENDPOINT
  OTEL_EXPORTER_OTLP_PROTOCOL
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
  OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
  OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
  OTEL_EXPORTER_OTLP_LOGS_PROTOCOL
  OTEL_TRACES_EXPORTER
  OTEL_METRICS_EXPORTER
  OTEL_LOGS_EXPORTER
  OTEL_RESOURCE_ATTRIBUTES
  CLAUDE_CODE_ENABLE_TELEMETRY
)

for name in $vars; do
  launchctl unsetenv "$name" || true
done

print "User launchd OpenTelemetry environment was removed. Restart apps to clear inherited values."
